# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements: 
        - docs
  system_packages: true

sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

