name: vtspy
channels:
  - fermi/label/dev
  - fermi
  - conda-forge
dependencies:
  - python
  - pyyaml
  - numpy>=1.16
  - scipy
  - astropy
  - matplotlib>=3.3
  - healpy
  - astropy-healpix
  - gammapy>=0.2
  - fermitools>=2.1.0
  - sphinx>=3
  - nbsphinx
  - sphinx-rtd-theme
  - myst-parser
  - ipykernel
  - sphinx-argparse
  - pygments==2.7.4
