name: vtspy
channels:
  - fermi/label/dev
  - fermi
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3 
  - clhep=2.4.4.1
  - pyyaml
  - numpy>=1.16
  - scipy
  - astropy
  - matplotlib>=3.3
  - healpy
  - uproot
  - html2text
  - astropy-healpix
  - gammapy>=0.2
  - fermitools>=2.1.0
  - fermipy
  - gammapy
  - pip:
    - -r docs/requirements.txt
