name: vtspy
channels:
  - fermi/label/dev
  - fermi
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3 
  - fermitools>=2
  - clhep=2.4.4.1
  - numpy
  - scipy
  - astropy
  - matplotlib
  - pyyaml
  - uproot
  - html2text
  - astropy-healpix
  - gammapy>=0.2
  - pip:
    - -r docs/requirements.txt
