fermi:
  binning:
    binsperdec: 8
    binsz: 0.08
    coordsys: CEL
    projtype: WCS
    roiwidth: 12
  data:
    evfile: ./fermi/EV00.lst
    ltcube: null
    scfile: ./fermi/SC00.fits
  fileio:
    logfile: ./fermi/log/fermipy.log
    outdir: ./fermi/
    usescratch: false
  gtlike:
    edisp: true
    edisp_disable:
    - isodiff
    - galdiff
    irfs: P8R3_SOURCE_V3
  model:
    catalogs: /Users/dtak/Research/scripts/vts-fermi/vtspy/refdata/gll_psc_v22.fit
    galdiff: $FERMI_DIFFUSE_DIR/gll_iem_v07.fits
    isodiff: $FERMI_DIFFUSE_DIR/iso_P8R3_SOURCE_V3_v1.txt
    src_roiwidth: 12
  selection:
    dec: 30.17694222440679
    emax: 300000
    emin: 100
    evclass: 128
    evtype: 3
    glat: 82.73442268671826
    glon: 186.3593855387067
    ra: 185.3412470056114
    target: 1ES1218+304
    tmax: 599616005.0
    tmin: 599529605.0
    zmax: 105
veritas:
  background:
    distance: 1.75
    file: Hipparcos_MAG8_1997
    magnitude: 7
  cuts:
    bias_cut: 0
    eff_cut: 0
    th2cut: 0.008
  fileio:
    outdir: ./veritas/
  selection:
    dec: 30.17694222440679
    emax: 2.0
    emin: 0.1
    exc_on_region_radius: 0.7
    exc_radius: 0.25
    format: mjd
    glat: 82.73442268671826
    glon: 186.3593855387067
    max_region_number: 6
    ra: 185.3412470056114
    radius: 2.0
    target: 1ES1218+304
    tmax: 58849.552106979165
    tmin: 58849.46887128472
